#!/usr/bin/python
# -*- coding: UTF-8 -*-

class Student:
   '?ùóD?§éúμ?D??￠'
   stuCount = 0
   maleCount = 0
   femaleCount = 0
 
   def __init__(self,number,name,stuclass,gender):
      self.stu_no = number
      self.name = name
      self.stu_class = stuclass
      self.gender = gender
      Student.stuCount += 1
      if gender == 'male':
         Student.maleCount += 1
      else:
         gender == 'female'
         Student.femaleCount += 1
     

   def study(self):
      print "Student can study"
 
   def getStuCount(self):
      print Student.stuCount


class PrimaryStudent(Student):
   primarystuCount = 0
   maleCount = 0
   femaleCount = 0
                     
   def __init__(self,number,name,stuclass,gender):
      self.stu_no = number
      self.name = name
      self.stu_class = stuclass
      self.male = gender
      Student.stuCount += 1
      PrimaryStudent.primarystuCount += 1
      if gender == 'male':
         Student.maleCount += 1
      else:
         gender == 'female'
         Student.femaleCount += 1
      
   def Recite(self):
      print "Primary Student can recite"
 
   def Oral(self):
      print "Primary Student can oral"


class MiddleStudent(Student):
   middlestuCount = 0
   maleCount = 0
   femaleCount = 0
   
   def __init__(self,number,name,stuclass,gender):
      self.stu_no = number
      self.name = name
      self.stu_class = stuclass
      self.male = gender
      Student.stuCount += 1
      MiddleStudent.middlestuCount += 1
      if gender == 'male':
         Student.maleCount += 1
      else:
         gender == 'female'
         Student.femaleCount += 1
      
      
   def Chemistry(self):
      print "Middle Student can chemistry"
 
   def Pyhics(self):
      print "Middle Student can pyhics"
